### ISSUE TITLE
mpileup2sync.jar not using multiple threads

### ISSUE THREAD

**Issue by orijitghosh** [popgenvienna/popoolation2#1]
Hi, I am using the folliwng command:
`java -ea -Xmx10g -jar ./popoolation2_1201/mpileup2sync.jar --input C1_L1_C2_L2_C3_L3_C4_L4_ag_new.mpileup --output C1_L1_C2_L2_C3_L3_C4_L4_ag_java.sync --fastq-type sanger --min-qual 30 --threads 10`
But the process is slow, and does not use multiple threads. Any idea what I am doing wrong? Thanks in anticipation.

**Comment by robmaz** [comment]
Sorry, I just forked this here from sourceforge. Try asking the author directly (Robert Kofler).
